// <auto-generated />
using System;
using Empresa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empresa.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20240614000316_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empresa.Models.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudad");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            Nombre = "Guadalajara"
                        },
                        new
                        {
                            CiudadId = 2,
                            Nombre = "Zapopan"
                        },
                        new
                        {
                            CiudadId = 3,
                            Nombre = "Tlaquepaque"
                        },
                        new
                        {
                            CiudadId = 4,
                            Nombre = "Tonala"
                        });
                });

            modelBuilder.Entity("Empresa.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Empresa.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<int?>("CiudadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Sueldo")
                        .HasColumnType("float");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("CiudadId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Empresa.Models.EmpleadoDepartamento", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId", "DepartamentoId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("EmpleadoDepartamento");
                });

            modelBuilder.Entity("Empresa.Models.Empleado", b =>
                {
                    b.HasOne("Empresa.Models.Ciudad", null)
                        .WithMany("Empleado")
                        .HasForeignKey("CiudadId");
                });

            modelBuilder.Entity("Empresa.Models.EmpleadoDepartamento", b =>
                {
                    b.HasOne("Empresa.Models.Departamento", "Departamento")
                        .WithMany("EmpleadoDepartamento")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empresa.Models.Empleado", null)
                        .WithMany("EmpleadoDepartamento")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Empresa.Models.Ciudad", b =>
                {
                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Empresa.Models.Departamento", b =>
                {
                    b.Navigation("EmpleadoDepartamento");
                });

            modelBuilder.Entity("Empresa.Models.Empleado", b =>
                {
                    b.Navigation("EmpleadoDepartamento");
                });
#pragma warning restore 612, 618
        }
    }
}
